data <- read.csv("../../data/averaged_data.csv")

cat("Summary statistics for Page Size (KB):\n")
cat("Mean:", mean(data$page_size_avg), "\n")
cat("Median:", median(data$page_size_avg), "\n")
cat("Minimum:", min(data$page_size_avg), "\n")
cat("Maximum:", max(data$page_size_avg), "\n")
cat("Standard deviation:", sd(data$page_size_avg), "\n\n")

cat("Summary statistics for Load Time (s):\n")
cat("Mean:", mean(data$load_time_avg), "\n")
cat("Median:", median(data$load_time_avg), "\n")
cat("Minimum:", min(data$load_time_avg), "\n")
cat("Maximum:", max(data$load_time_avg), "\n")
cat("Standard deviation:", sd(data$load_time_avg), "\n\n")

cat("Summary statistics for log(Page Size):\n")
cat("Mean:", mean(log(data$page_size_avg)), "\n")
cat("Median:", median(log(data$page_size_avg)), "\n")
cat("Minimum:", min(log(data$page_size_avg)), "\n")
cat("Maximum:", max(log(data$page_size_avg)), "\n")
cat("Standard deviation:", sd(log(data$page_size_avg)), "\n\n")

cat("Summary statistics for log(Load Time):\n")
cat("Mean:", mean(log(data$load_time_avg)), "\n")
cat("Median:", median(log(data$load_time_avg)), "\n")
cat("Minimum:", min(log(data$load_time_avg)), "\n")
cat("Maximum:", max(log(data$load_time_avg)), "\n")
cat("Standard deviation:", sd(log(data$load_time_avg)), "\n")
